[package]
name = "snipt-core"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
rdev = { workspace = true }
enigo = { workspace = true }
thiserror = { workspace = true }
